l_spanish:
 productionbuffs:0 "Impulso de Producción"
 icon:0 "Impulso de Producción"
 productionbuffs1:0 "50% de Aumento de la Producción"
 productionbuffs_1:0 "50% de Aumento de la Producción"
 productionbuffs2:0 "100% de Aumento de la Producción"
 productionbuffs_2:0 "100% de Aumento de la Producción"
 productionbuffs3:0 "250% de Aumento de la Producción"
 productionbuffs_3:0 "250% de Aumento de la Producción"
 productionbuffs4:0 "1000% de Aumento de la Producción"
 productionbuffs_4:0 "1000% de Aumento de la Producción"
