l_english:
productionbuffs:0 "Overall Production Boost"
icon:0 "Overall Production Boost"
productionbuffs1:0 "50% Overall Production Boost"
productionbuffs_1:0 "50% Overall Production Boost"
productionbuffs2:0 "100% Overall Production Boost"
productionbuffs_2:0 "100% Overall Production Boost"
productionbuffs3:0 "250% Overall Production Boost"
productionbuffs_3:0 "250% Overall Production Boost"
productionbuffs4:0 "1000% Overall Production Boost"
productionbuffs_4:0 "1000% Overall Production Boost"